name: challenge
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  go_router: ^16.2.4
  bloc: ^9.0.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.0
  meetup_client:
    path: packages/meetup_client
  meetup_repository:
    path: packages/meetup_repository
  app_ui:
    path: packages/app_ui

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  bloc_test: ^10.0.0
  mocktail: ^1.0.4
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true