name: app_ui
description: App UI library
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.5.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_asset_generator: ^1.0.2
  flutter_svg: ^2.0.10+1


dev_dependencies:
  build_runner: ^2.4.4
  flutter_gen_runner: ^5.4.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_gen:
  assets:
    enabled: true
    outputs:
      package_parameter_enabled: true
  output: lib/src/generated/
  line_length: 80

  integrations:
    flutter_svg: true
